### PR TITLE
Add LoongArch cpu support.

### PR DESCRIPTION
**Pull request by zangruochen**
LoongArch is a new architecture that is already supported by linux-6.1, gcc-12, and I want to add LoongArch support for c4core.

### CODE REVIEW

**Comment by biojppm** [comment]
Thanks for the MR, much appreciated! Is there a github action with this architecture?

**Comment by zangruochen** [comment]
Sorry, we don't have a github action with LoongArch architecture yet.

**Comment by zangruochen** [comment]
@biojppm Hi, I would like to ask if having github action is necessary for adding new architecture support, and if so, can you provide me some guidance on adding architecture related github action for this project.

**Comment by biojppm** [comment]
Sorry for the late reply. No, it is not needed, though it would be nice.

**Comment by biojppm** [comment]
Thanks for the PR!

**Pull request merged**
