### PR TITLE
[impl] add riscv cpu support

### PR DESCRIPTION
**Pull request by Xeonacid**
Since https://github.com/uraimo/run-on-arch-action doesn't support riscv currently, I'm not adding any test. I will try hard to add support for it.

### CODE REVIEW

**Comment by biojppm** [comment]
I had trouble finding any action running on RISC-V. Was hoping you knew of one, even outside run-on-arch. 

Anyway, if there is no action, we'll have to stick to the old fashioned (risky) way. Have you tried this changeset yourself? That is, does this changeset enable the c4core tests to successfully run in RISC-V, or is anything else required? You can try it like this:
```
cmake -S c4core -B c4core-build -D C4CORE_DEV=ON
cmake --build c4core-build --target c4core-test-run
```

**Comment by biojppm** [comment]
Also you can update the cmake submodule. It's not required, but makes sense since the changesets are related.

**Comment by Xeonacid** [comment]
@biojppm I find that run-on-arch has an open PR https://github.com/uraimo/run-on-arch-action/pull/58 which adds support for RISC-V. But I doubt when it can be merged, sadly.

> Also you can update the cmake submodule. It's not required, but makes sense since the changesets are related.

OK. I will do that soon.

**Comment by biojppm** [comment]
@Xeonacid thanks for the info on that RISC-V PR; was not aware of it.

To merge this PR, I'm just waiting on your confirmation that this changeset runs the c4core tests in RISC-V, as described above. (The coverage test failures are spurious; everything else looks good).

**Comment by Xeonacid** [comment]
@biojppm I just ran it on Arch Linux RISC-V, and all tests passed except the ones using valgrind. (Valgrind does not support RISC-V now. :cry: )


<details>
<summary>Logs</summary>

```text
Could not find executable valgrind
Looked in the following places:
valgrind
valgrind
Release/valgrind
Release/valgrind
Debug/valgrind
Debug/valgrind
MinSizeRel/valgrind
MinSizeRel/valgrind
RelWithDebInfo/valgrind
RelWithDebInfo/valgrind
Deployment/valgrind
Deployment/valgrind
Development/valgrind
Development/valgrind
Unable to find executable: valgrind
138/138 Test #138: c4core-test-std_vector-valgrind ........***Not Run   0.00 sec

83% tests passed, 23 tests failed out of 138

Total Test time (real) =  12.00 sec

The following tests FAILED:
          6 - c4core-test-preprocessor-valgrind (Not Run)
         12 - c4core-test-type_name-valgrind (Not Run)
         18 - c4core-test-types-valgrind (Not Run)
         24 - c4core-test-szconv-valgrind (Not Run)
         30 - c4core-test-error-valgrind (Not Run)
         36 - c4core-test-error_exception-valgrind (Not Run)
         42 - c4core-test-blob-valgrind (Not Run)
         48 - c4core-test-memory_util-valgrind (Not Run)
         54 - c4core-test-memory_resource-valgrind (Not Run)
         60 - c4core-test-allocator-valgrind (Not Run)
         66 - c4core-test-ctor_dtor-valgrind (Not Run)
         72 - c4core-test-chartraits-valgrind (Not Run)
         78 - c4core-test-enum-valgrind (Not Run)
         84 - c4core-test-bitmask-valgrind (Not Run)
         90 - c4core-test-span-valgrind (Not Run)
         96 - c4core-test-substr-valgrind (Not Run)
        102 - c4core-test-charconv-valgrind (Not Run)
        108 - c4core-test-utf-valgrind (Not Run)
        114 - c4core-test-format-valgrind (Not Run)
        120 - c4core-test-dump-valgrind (Not Run)
        126 - c4core-test-base64-valgrind (Not Run)
        132 - c4core-test-std_string-valgrind (Not Run)
        138 - c4core-test-std_vector-valgrind (Not Run)
```


</details>

**Comment by biojppm** [comment]
Thanks @Xeonacid !

**Pull request merged**
